server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: hwryu990927!
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Work/native-file-repo
        git:
          uri: git@github.com:uhanuu/spring-cloud-config.git
          ignoreLocalSshSettings: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEArDxiUgXEJhHgy4HG5orfa3wp3ooVnmFTHynhyVRHViJz2Dye
            g/NsbsgbUyCtmpDmzmcDvpK6E1jYVEG8+VNigmsIqyTxeBnCRJyF4DCg+py9oIJI
            fF+1hssVYVLNtLfyqqu8o4kIatVvbUqRrIq4+aAFPWdCv81McNOUQajUwPedP2y/
            K7q3Vxshmft6GcAcw4IiQIDD+IwV/HtRj5hiofqWK8vQNkyhPWKA/eplCtJ9AI0X
            goAmiLKQ7f/7dWqAH5EZv3CCPhI0vIi6pedQ8zVV8CSIXkUo0zkWSqlPTFdjNQF4
            kNyz++Qts4sr8Sag8Ya0NjrPySUjaj/qNnACt5+psKkR09Apm0RiYSxo8FUHzmMw
            xBNRE05hGA6AR+i52TIpMgFMEzoVuakqEUJ3WZz6uanzJaTLCPnOLTPzefKW6jnS
            8cz+QHb43ZP1wOdOcnpyVWye0DXfVTBhLglP5ULpKB0/j3xe09680H9p+svzNeRH
            k3OTPbUhdqcCIuXns5CdDd8l5p94zPCyehbFHF9mTnVozNHZcm3ml9GH9Uihx14Z
            NbjQLZXviA8DCX1llh5If1+YyJjORwqr3LcSuYKq+XVJqfodo7ZFmflzSRIBegZO
            9fCmdhfk2WjdTbpybtg9B8obCE7rzBKmf+SJzasH23mhKmKXGKGyKD4zj6kCAwEA
            AQKCAgBDJwfukvD3JuFOdzrliB+z+KUabxwetDOEYv/1TzbBDo28MWZca/xK9Roy
            Pvtw2C4lK2T6WJrUED/IGhlj3G78Cl9G2xCKkwB7X8uSrWMWUyZb/m/kjixocaXU
            XER3wYCLqonR+QufG7hmFDzX2P5l1U41sp0DyzeSheu37euFkQVuRSgEFLiG7b0c
            HEBu6chNMd/I5muB7Jxl5G7YXcGXBeynBsAXa6kyFcXVOh5LKeYy4M/Zwb1Ebtqy
            8KtKDEwIArrXOTaOnOqS13xuUtHtAU6QYq4Ik05njEp0sa6JRUkY0YoAcQx7mWt4
            JTrsuvLlOG/q9OMuuZwlQOZAc0ubSF3kzQr4FvZiHu9GnNoOrD+L1jIaBer5maMD
            i9ldn5seuJwOlVwA+odV7WJgBht65QkImekcjckHdRL5344YL5NrlAW6S60qDI/k
            d2/Gtv6kJJAm/f0zVW0dao4cmvhcaJ9uzGnxx22M4g83x5jMCXMlBY2ZxmbOJ0sm
            FoPpREn78NwIdxaMQ/mc80RbclSpciveXssAhuhiba/mE6q+rAU4Vnu0FPeNkNBY
            +FvxzxUcoEROxjUWAO3bXP8IBrL2nSHD21ibnPzMREvwnjGOmsZPZeQx/Y53u1zi
            LzmQyGK4RvpQmcbTvqvs2IJAUJlvDyW7DBrvpRq6nvIe4rRVAQKCAQEA3UbAjbRm
            LormhVVh5YH+pfmgvF/otbqaUNomy/yq0UfWOiokiPj5FUEq6tvTLE8W+1icaH8p
            +MB4Lb1JTvg9Px8tPPc+UNrE1HuBEpiZeMsy0WerzqOXybk0WolvLYC0gMjSw+t0
            VzcMUUqtZevNsd9LImrY/0QF0WAztXq6p4qNKgi2nSjdauWegLB8TqLFognNhhWd
            x1oTfl1XwnsHv6M1B5Voeypa9i4HKwquXFweyGR4aIh/q40A/wXmr86U4htpCZRr
            UgGH2GP5tBEvE1EvhR79jQZZD7IjO78s15VpNUHTtAYzYV6rGeM/n9lepF2qpo1Z
            gajdwq8bYpzbnQKCAQEAx0OMIUxijR3kyH6YPhQxlJ+mdfHgajOSbpKsLoHqbUdj
            bqvI2OE5qFqQdZs2d6pBBfEqh/fYf0LwWvMVuPqtvH0TosGWxuyaUKMFjIrbs7V4
            sfm3GdoGYeKc/c1qIQJpp7fnQ5mx0Fz0wt1wneU2iX6xSFP/qgEbNwSdLQ+BKxhg
            9koHPIxPoddMw/3/KFA6I0JehhLo+HRgelVGb2IGJ1UXHB/9Kfl5acFny+A1ghwa
            oL3iob661xhGGNleAYup/w3e/zhNBxVxndbWMNfLUvUeTLusY57wNa1durSmjquk
            jsHmdbTWJ75iz5MSjdlQUplq1b4ZA3OaUDd9gC9kfQKCAQBujjMWmdOT3YJfi9Fl
            whVhB9/vPlwesCT50IUh1hPijGnUlcm7RentXKn8veg8cyegXR2IeECYMFHbSH+g
            HRc8um73zvArpaJCJ5LNn8DOQXgaeBm3HLVx7D7kHVaW/X8x+SSVDscJ7E8TLqSE
            D9St0krP32Kb53igq9gqDC/GFcuB/OiAjTJTfnY7BfKVt23XD97H53T1bWPf9vMq
            EB5G+Vw9dcDGCNt5tHWQY73KF5ypsskWMVzYcZLV2DTyEd0BO4C3cJhOWMVusETK
            WuuSUzXS5TD5jPpihTZlW5cj/1qZaVJE1/RD6fDC9m+LhidrKAFjRaw6xAxIgQTF
            uGlhAoIBAQCyCQUb/z6SbSIrjQiDdtFxxE8bVHg5C0kLKFtU1ljZOI57pFq4hEta
            w0gM/BfnRSQBph9lCqnR0sIj0MsY0kkGfw5bPfJ0W5Po9i8QCkUQRNTI15+kJmvL
            a4jvL2hig+BYrPShLqJz04oQzX9AZDqdEKhfQkXM5F4ngyTXzOGQ2qBPjYb3rzm7
            FT2OY9NldoDrXfJMgnrK+lf1FVnwTLnIzLrwMxikNzUmq1oNC49jZ67W7bGe6GXR
            puuCajwWz22c6AzVJb2U1bEE4J3RWA1fWoiu8IOvIqPmobZ8CcpC8NL/hfleM6ug
            KPfqFLLgMEkW8+JDhSyeK9y1TU8Bh9aVAoIBABJMgwhZ2H7B8r1yGKAsmDzZWPSJ
            GcCx4Sl/Yw1uaZWh1qhvNmaS+hZlpujb+zhevJx9y6ymk1lzEB0Vu2evAq8IpApN
            qyTN+oamCXM9vGX+DCF7ayB5S8WSAlOf9Rw8hnpC1G0jfAeYYRpLWmk532rpQHlC
            XQeCcCGjRqr7Ajsn5usL14X7IM6GZSwhNDQNu87Hsx7u2DAWKVnpa+nURbevtAoo
            xJgOlmRXKOezJeT+d68i8xpYR62SaR9AR85XRy5+g0U0BidhBXDc73N39pONNHI+
            EdUPhfP7lt3PbR9ZD+qGeHC6P0qkizG8FW1YlVXFqgFm1Z5ouo2ZGEJwB1c=
            -----END RSA PRIVATE KEY-----

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh